//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentIO.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionControlNumber
    {
        public int SelectionCampaignId { get; set; }
        public string SpecialityCode { get; set; }
        public int NumberOfStudent { get; set; }
        public int FormOfEducationId { get; set; }
        public bool IsPaidBasis { get; set; }
    
        public virtual FormOfEducation FormOfEducation { get; set; }
        public virtual SelectionCampaign SelectionCampaign { get; set; }
        public virtual Speciality Speciality { get; set; }
    }
}
