//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentIO.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionControlNumber
    {
        public int SelectionCampaignId { get; set; }
        public string SpecialityCode { get; set; }
        public int NumberOfStudent { get; set; }
        public int FormOfEducationId { get; set; }
        public bool IsPaidBasis { get; set; }
    
        public virtual FormOfEducation FormOfEducation { get; set; }
        public virtual SelectionCampaign SelectionCampaign { get; set; }
        public virtual Speciality Speciality { get; set; }
    }
}
