//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentIO.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enrollee()
        {
            this.EnrolleeEntranceTest = new HashSet<EnrolleeEntranceTest>();
            this.PersonalStudentFile = new HashSet<PersonalStudentFile>();
        }
    
        public int IdEnrollee { get; set; }
        public string FirstNameEnrollee { get; set; }
        public string SecondNameEnrollee { get; set; }
        public string MiddleNameEnrollee { get; set; }
        public System.DateTime DateOfBirthday { get; set; }
        public string NationalityCode { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string Email { get; set; }
        public int StatementId { get; set; }
        public Nullable<int> DocumentId { get; set; }
    
        public virtual EnrolleeDocument EnrolleeDocument { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual Statement Statement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrolleeEntranceTest> EnrolleeEntranceTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalStudentFile> PersonalStudentFile { get; set; }
    }
}
