//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentIO.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrolleeDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnrolleeDocument()
        {
            this.Enrollee = new HashSet<Enrollee>();
        }
    
        public int IdDocument { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public string IssuingAuthority { get; set; }
        public bool PhotosProvided { get; set; }
        public string ActualAdress { get; set; }
        public string RegistrationAdress { get; set; }
        public string CertificateSerias { get; set; }
        public string CertificateNumber { get; set; }
        public Nullable<double> CertificateScore { get; set; }
        public string DiplomSerias { get; set; }
        public string DiplomNumber { get; set; }
        public Nullable<double> DiplomScore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollee> Enrollee { get; set; }
    }
}
