//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentIO.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderOfAdmission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderOfAdmission()
        {
            this.PersonalStudentFile = new HashSet<PersonalStudentFile>();
        }
    
        public string NumberOrderOfAdmission { get; set; }
        public System.DateTime DateOfSigning { get; set; }
        public int SelectionCampaignId { get; set; }
    
        public virtual SelectionCampaign SelectionCampaign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalStudentFile> PersonalStudentFile { get; set; }
    }
}
