//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentIO.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderOfAdmission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderOfAdmission()
        {
            this.PersonalStudentFile = new HashSet<PersonalStudentFile>();
        }
    
        public string NumberOrderOfAdmission { get; set; }
        public System.DateTime DateOfSigning { get; set; }
        public int SelectionCampaignId { get; set; }
    
        public virtual SelectionCampaign SelectionCampaign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalStudentFile> PersonalStudentFile { get; set; }
    }
}
