//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentIO.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalStudentFile
    {
        public int IdPersonalFile { get; set; }
        public int EnrolleeId { get; set; }
        public int GroupId { get; set; }
        public string OrderOfAdmissionNumber { get; set; }
    
        public virtual Enrollee Enrollee { get; set; }
        public virtual Group Group { get; set; }
        public virtual OrderOfAdmission OrderOfAdmission { get; set; }
    }
}
