//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentIO.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalStudentFile
    {
        public int IdPersonalFile { get; set; }
        public int EnrolleeId { get; set; }
        public int GroupId { get; set; }
        public string OrderOfAdmissionNumber { get; set; }
    
        public virtual Enrollee Enrollee { get; set; }
        public virtual Group Group { get; set; }
        public virtual OrderOfAdmission OrderOfAdmission { get; set; }
    }
}
