//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentIO.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Statement()
        {
            this.Enrollee = new HashSet<Enrollee>();
        }
    
        public int IdStatement { get; set; }
        public System.DateTime DateOfFilling { get; set; }
        public string SpecialityCode { get; set; }
        public int SelectionCampaignId { get; set; }
        public bool IsFullTimeEducation { get; set; }
        public bool FreeEducation { get; set; }
        public bool Dormitory { get; set; }
        public int StartEducationId { get; set; }
        public bool IsFirstEducation { get; set; }
        public bool AquantedStatute { get; set; }
        public bool AquantedLicense { get; set; }
        public bool AquantedEvidence { get; set; }
        public bool AquantedEducationProgramm { get; set; }
        public bool AquantedRulesOfAdmission { get; set; }
        public bool AquantedInternalRegulations { get; set; }
        public bool AquantedSubmissionOfDocument { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollee> Enrollee { get; set; }
        public virtual SelectionCampaign SelectionCampaign { get; set; }
        public virtual Speciality Speciality { get; set; }
        public virtual StartEducation StartEducation { get; set; }
    }
}
