//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentIO.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectOfEntranceTest
    {
        public int EntranceTestId { get; set; }
        public int SubjectId { get; set; }
        public int SubjectPriority { get; set; }
    
        public virtual EntranceTest EntranceTest { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
